server:
  port: 8080

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      ssl:
        enabled: false

  jwt:
    secret: ${JWT_SECRET}

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "https://cafe.beetledev.kr"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${CLOUD_GATEWAY_AUTH}
          predicates:
            - Path=/login,/auth/**

        - id: store-service
          uri: ${CLOUD_GATEWAY_STORE}
          predicates:
            - Path=/stores/**,/menus/**

        - id: notification-service
          uri: ${CLOUD_GATEWAY_NOTI}
          predicates:
            - Path=/notification/**

management:
  endpoint:
    health:
      show-details: always

gateway:
  secret: ${GATEWAY_SECRET}

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG