server:
  port: 8080

spring:
  config:
    import: "aws-secretsmanager:prd/cafe"

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true

  jwt:
    secret: ${JWT_SECRET}

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - ${ALLOWED_ORIGIN_ADMIN}
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth-service
          uri : ${CLOUD_GATEWAY_AUTH}
          predicates:
            - Path=/login,/auth/**

        - id: store-service
          uri : ${CLOUD_GATEWAY_STORE}
          predicates:
            - Path=/stores/**,/menus/**

        - id: notification-service
          uri : ${CLOUD_GATEWAY_NOTI}
          predicates:
            - Path=/notification/**

gateway:
  secret: ${GATEWAY_SECRET}