spring:
  config:
    import: "aws-secretsmanager:cafe/api-gateway"

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true

  jwt:
    secret: ${ JWT_SECRET }

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri : ${ CLOUD_GATEWAY_AUTH }
          predicates:
            - Path=/login,/auth/**

        - id: store-service
          uri : ${ CLOUD_GATEWAY_STORE }
          predicates:
            - Path=/stores/**,/menus/**

        - id: notification-service
          uri : ${ CLOUD_GATEWAY_NOTI }
          predicates:
            - Path=/notification/**

gateway:
  secret: ${ GATEWAY_SECRET }